name: Send Email

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
            # For posting a rich message using Block Kit
        payload: |
          {  
            "text": "PITO Partner Staging has built successully",
            "attachments": [
            {
              "pretext": "Android App",
              "color": "28a745",
              "fields": [
                {
                  "title": "Status",
                  "short": true,
                  "value": "Completed"
                }
              ]
            }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
