name: Slack Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "*${{ github.repository }} - New Commit*",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "New commit in ${{ github.repository }}",
                "text": "A new commit has been pushed to the repository.",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}",
                    "short": false
                  },
                  {
                    "title": "Author",
                    "value": "${{ github.event.head_commit.author.name }}",
                    "short": true
                  },
                  {
                    "title": "Commit URL",
                    "value": "${{ github.event.head_commit.url }}",
                    "short": true
                  }
                ],
                "footer": "GitHub Actions",
                "ts": "$(date +%s)"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
