name: Send Email

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have requirements.txt with necessary packages

    - name: Send email
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USERNAME: althurzard@gmail.com
        SMTP_PASSWORD: Quocvuong@1993
        EMAIL_TO: 773b27e0.orthian.vn@apac.teams.ms
        EMAIL_FROM: althurzard@gmail.com
      run: |
        echo "Subject: Your subject here" > message.txt
        echo "Your email body here" >> message.txt
        echo "" >> message.txt
        echo "Best regards," >> message.txt
        echo "Your Name" >> message.txt
        cat message.txt | sendmail -v -S $SMTP_SERVER:$SMTP_PORT -xu $SMTP_USERNAME -xp $SMTP_PASSWORD -f $EMAIL_FROM $EMAIL_TO
