name: Send Email

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
            # For posting a rich message using Block Kit
        payload: |
           {
            "text": "*${{ github.repository }} - New Commit*",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "New commit in ${{ github.repository }}",
                "text": "A new commit has been pushed to the repository.",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}",
                    "short": false
                  },
                  {
                    "title": "Author",
                    "value": "${{ github.event.head_commit.author.name }}",
                    "short": true
                  },
                  {
                    "title": "Commit URL",
                    "value": "${{ github.event.head_commit.url }}",
                    "short": true
                  }
                ],
                "footer": "GitHub Actions",
                "ts": "$(date +%s)"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
