name: Send Email

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose Python version

    - name: Send email
      env:
        SMTP_SERVER: smtp.office365.com
        SMTP_PORT: 587
        SMTP_USERNAME: vuong.nguyen@orthian.vn
        SMTP_PASSWORD: TZ4ia9.-t5z-md2
        EMAIL_TO: 773b27e0.orthian.vn@apac.teams.ms
        EMAIL_FROM: vuong.nguyen@orthian.vn
      run: |
        python - <<EOF
        import smtplib
        from email.message import EmailMessage
        
        msg = EmailMessage()
        msg['Subject'] = 'Your subject here'
        msg['From'] = '$EMAIL_FROM'
        msg['To'] = '$EMAIL_TO'
        msg.set_content('Your email body here\n\nBest regards,\nYour Name')
        
        with smtplib.SMTP('$SMTP_SERVER', $SMTP_PORT) as smtp:
            smtp.starttls()
            smtp.login('$SMTP_USERNAME', '$SMTP_PASSWORD')
            smtp.send_message(msg)
        EOF
