# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  send_messages:
      name: send message to MS Team
      runs-on: ubuntu-latest
      steps:
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: https://prod-13.southeastasia.logic.azure.com:443/workflows/c6ed4cafeb3e49e68adbd7b57ed06611/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=sAV2DplXhipR1z2yHk1blg5SWOIFgBWu3JtUgTxyJa4   # Secret name is "TEAMS_INCOMING_WEBHOOK_URL"
          message: Workflow run passed test abcsds !!
